### PR TITLE
Initial work on adding internationalization.

### PR DESCRIPTION
**Pull request by MFAshby**
From https://github.com/JF002/InfiniTime/issues/363

This commit adds [lv_i18n](https://github.com/lvgl/lv_i18n) tooling for translating user-facing strings. It also adds a new settings page to allow selecting between up to 4 languages.

Done:
[X] Language selector for the settings screen (caveat, this can only support up to 4 languages at the moment)
[X] Replace hard-coded english text with lookups (done most text I can find) 
[X] Update main README for contributing translations

Known issue:
Some characters aren't rendering properly, for example `Batería` is rendering as `Batera` in the settings menu.

Known limitation:
The settings screen will only support up to 4 languages.

TODO:
[ ] Fix rendering issues for characters outside the usual ASCII
[ ] Calculate firmware size increase due to translations
[ ] If unacceptably large, either: 
1. build multiple firmwares, one for each language, and remove the user selection at runtime. 
2. wait until external flash memory can be used, and store strings files in it https://github.com/JF002/InfiniTime/issues/321

### CODE REVIEW

**Comment by MFAshby** [comment]
DFU from this branch
[pinetime-mcuboot-app-dfu-1.2.0.zip](https://github.com/JF002/InfiniTime/files/6712239/pinetime-mcuboot-app-dfu-1.2.0.zip)

**Comment by MFAshby** [comment]
Grainy photos of settings screen and (probably badly) translated menu.
IMG_20210624_223227466
IMG_20210624_223252025

**Comment by Avamander** [comment]
Needs rebasing, it's probably easier to do incrementally than in big batches. Definitely something that'll be part of InfiniTime at some point and this PR is a great start.

**Comment by MFAshby** [comment]
Practically it's probably better to just start again with these code changes, they were quite simple.

**Pull request closed without merging**
