### PR TITLE
fixing my boneheaded mistake

### PR DESCRIPTION
**Pull request by Raupinger**
thanks to @Avamander and @MysteriousLog6 for noticing this. I'm honestly surprised that code even compiled.

### CODE REVIEW

**Comment by MysteriousLog6** [comment]
Seems to have fixed it the compiler warning is no more.

**Comment by JF002** [comment]
For my own comfort when reviewing PRs, could you be a bit more specific in the title/description?

Ok, I've had a look at the code. How come no one (me included) noticed that?

So, yes, it compiles because, for the compiler
```
    pchar =
    pchar = strchr(pchar + 1, '\n');
```
is the same than 
```
    pchar = pchar = strchr(pchar + 1, '\n');
```
which is probably optimized with
```
    pchar = strchr(pchar + 1, '\n');
```

**Comment by Raupinger** [comment]
> Ok, I've had a look at the code. How come no one (me included) noticed that?

Avamander did. I just completely missed his point.

**Comment by JF002** [comment]
@Avamander My apologies I missed that while reviewing the PR!

**Pull request merged**
