### PR TITLE
Modify status text in BatteryInfo so it fits on screen

### PR DESCRIPTION
**Pull request by kieranc**
See issue #433 
I've changed 'Battery is fully charged' to simply 'Battery charged' so it fits on screen. I also modified 'Battery is low' to 'Battery low' for consistency.

'Battery fully charged' would have been preferable IMO, but it doesn't fit. If anyone has a strong opinion on the matter I could make the text scroll instead, but for a small overflow it seems better to do it this way.

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
better solution than mine

**Comment by JF002** [comment]
> 'Battery fully charged' would have been preferable IMO, but it doesn't fit. 

Maybe it could fit on 2 lines?

**Comment by kieranc** [comment]
> > 'Battery fully charged' would have been preferable IMO, but it doesn't fit.
> 
> Maybe it could fit on 2 lines?

That might not fit between the charging bar and the voltage text below. I'm happy with this as a solution, but I can try it over 2 lines if you prefer.

**Comment by JF002** [comment]
> That might not fit between the charging bar and the voltage text below, it'll be cramped if it does. I'm happy with this as a solution, but I can try it over 2 lines if you prefer.

Both solutions are ok for me, let's choose the one that looks best :)

**Comment by kieranc** [comment]
batteryinfo1
batteryinfo2

Here are the 2 options in the simulator, colours are incorrect but the alignment is accurate. I.... don't really have strong feelings either way? Which do you prefer?

**Comment by JF002** [comment]
That's a great use of the simulator, thanks for trying both options! I personally  like the 2nd one (2 lines). 
Does anyone else have an opinion about this?

**Comment by kieranc** [comment]
> That's a great use of the simulator, thanks for trying both options! I personally like the 2nd one (2 lines).
> Does anyone else have an opinion about this?

Updated to the 2 line option - the only issue in my eyes is that all other messages are now a single line and fully charged is 2.

**Comment by Itai-Nelken** [comment]
The single line looks better in my opinion

**Comment by Itai-Nelken** [comment]
The single line looks better in my opinion, but the text in it isn't good. `battery charged` doesn't sound good to me, maybe simply put `charged` or `fully charged`?

**Comment by kieranc** [comment]
I quite like the 'Fully charged' concept since 'Battery' is implied, given we're in the battery app, an there's nothing else on the device which can be charged. We have 4 text elements to define, so:

1, Current, Battery is fully charged doesn't fit on one line.
- Battery charging
- Battery is fully charged
- Battery is low
- Battery discharging

2, Not keen on the similarity between charged and charging
- Battery charging
- Battery charged
- Battery low
- Battery discharging

3, Too short
- Charging
- Fully charged
- Low
- Discharging

4, Also a bit short
- Charging
- Fully charged
- Battery low
- Discharging

5, Feels pretty good to me
- Battery charging
- Fully charged
- Battery low
- Battery discharging


I think I'd prefer to keep it all on one line, or have them all on 2 lines, and I don't think there's enough text to justify 2 lines.

**Comment by Riksu9000** [comment]
I like the 4th option. I don't think it's too short, unless it looks weird in app? Maybe it could say "Almost empty" for battery low.

**Comment by kieranc** [comment]
> I like the 4th option. I don't think it's too short, unless it looks weird in app? Maybe it could say "Almost empty" for battery low.

I kind of thought the same thing after my last comment... here's how it looks:

batopt4s1
batopt4s2
batopt4s3
batopt4s4

**Comment by JF002** [comment]
If everyone agree with this last suggestion, let's do it ;)

**Comment by kieranc** [comment]
Sounds good to me, ready to merge I think.

**Comment by JF002** [comment]
Great, thanks!

**Pull request merged**
