### PR TITLE
Add VSCode ST-link debug config

### PR DESCRIPTION
**Pull request by hubmartin**
Add launch configuration for debugging PineTime with ST-link and OpenOCD.

You also need cortex-debug extension https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug
In VSCode Ctrl+P `ext install marus25.cortex-debug`

Open project, hit F5. (or Ctrl+Shift+D and choose Debug OpenOCD ST-LINK and click Play button)

- Breakpoints
- Variables
- Call stack
- NRF52 registers thanks to nrf52.svd
- ...

Not sure if this isn't mentioned in the documentation. I could write an short note, let me know where it would fit the best.

image

### CODE REVIEW

**Comment by geekbozu** [comment]
This has also been partially setup in PR #505 ...I just have not been able to test/build it on windows to confirm its working heh

**Comment by hubmartin** [comment]
I overlooked that. Good to see that config file is similar. It's always lot of crafting of those launch.json files. I can confirm that my setup works in Ubuntu. Looking forward for docker builds.

**Comment by geekbozu** [comment]
Yeah it took some effort on my end the first time...I'm just shooting to help get an easy to setup run and use toolchain for anyone who wants to play with it, and containers seem like the way to go... it would be super nice to have VSCode work locally as well for those who need it! So maybe after/during 1.4s milestone we can get these merged and support both in one run! Since local stuff currently I feel is out of the scope of my PR :)

**Comment by hubmartin** [comment]
In #505 there is not working local configuration, so this still makes sense to merge and add local non-docker debug with STLink/OOCD.

**Comment by hubmartin** [comment]
@JF002 Can you please merge it? Its just launch config for vscode, shoudn't broke anything :) I'm using it in few branches I have PRs and it is pain in the ass to copy it for every PR I need to debug with ST-Link. Thank you.

**Comment by JF002** [comment]
@hubmartin  Done ;)

**Pull request merged**
