### PR TITLE
docs: Fix a few typos

### PR DESCRIPTION
**Pull request by timgates42**
There are small typos in:
- doc/versioning.md
- src/components/ble/NimbleController.cpp
- src/systemtask/SystemTask.cpp

Fixes:
- Should read `unnecessary` rather than `uncesseray`.
- Should read `target` rather than `tharget`.
- Should read `functioning` rather than `functionning`.
- Should read `recommended` rather than `recomended`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

### CODE REVIEW

**Comment by geekbozu** [comment]
Nothing wrong fixing typos all are in comments. So +1

**Review by evergreen22 — APPROVED** [review]
Thanks

**Comment by JF002** [comment]
Thanks, that's a nice automation!

I noticed that it detected typos in  `src/libs/mynewt-nimble`. As this is an external library, can we avoid modifying them? Those changes will be lost next time we update the library, and also when we'll use submodule for these libs.

**Comment by evergreen22** [comment]
Good catch! I didn't see the nimble ones.

Agreed we should *not* modify upstream libraries in our repo.

I suggest the PR author submit a PR to nimble for the typos in their 
codebase.

**Comment by timgates42** [comment]
Thanks @evergreen22 have removed the nimble changes.

**Pull request merged**
