### PR TITLE
Update LVGL

### PR DESCRIPTION
**Pull request by joaquimorg**
Merge from upstrem :
 - fix(table) fix memory leak

### CODE REVIEW

**Comment by petterhs** [comment]
Is it updated to v7.11.0?

**Comment by joaquimorg** [comment]
We are already at 7.11.0 this is a fix
https://github.com/lvgl/lvgl/commits/release/v7

**Comment by MysteriousLog6** [comment]
I think the LVGL is a Submodule?

**Comment by joaquimorg** [comment]
> I think the LVGL is a Submodule?

Yes it is, but it is linked to a certain version of this module when there are updates we have to update that link to the new one.

**Comment by MysteriousLog6** [comment]
Can't we link it to the main branch

**Comment by pfeerick** [comment]
Submodule versions have to be pinned, otherwise you will have the "what version of the submodule is the code written for" issue. So when you want to use a newer version, you update the submodule version, which then brings in whatever changes were made in that repo.

**Pull request merged**
