### PR TITLE
Added a helper script for docker

### PR DESCRIPTION
**Pull request by shuhaowu**
Just a script to make recompiling in docker a little less typing. Simply invoke `docker/b` from the root of the repository.

### CODE REVIEW

**Comment by petterhs** [comment]
I also want this merged :) I have a similar script in docker/ that I have to make sure not gets added to my commits. The script could probably have a more describing name though. Something like docker-build maybe?

**Comment by shuhaowu** [comment]
The problem is that there is a script called build.sh already in the docker directory, which is copied into the container. Can name this script docker/build if we rename that other script ...

**Comment by pfeerick** [comment]
Why not just call it `docker-build.sh`..., i.e. `docker/docker-build.sh` ... after all, it's not that often you need to rebuild it, right?

**Comment by JF002** [comment]
I agree that the file could be renamed as something more expressive like `docker-build.sh`.

**Comment by JF002** [comment]
I close this PR since there was no activity since end of February. Feel free to reopen it if you want to continue your work.

**Pull request closed without merging**
