### PR TITLE
Slowly scrolls long titles/artists in music app

### PR DESCRIPTION
**Pull request by jedmijares**
Addresses #97 / #130.

### CODE REVIEW

**Comment by JF002** [comment]
Thanks for this PR and for [the video demonstrating that it works](https://github.com/JF002/Pinetime/issues/97#issuecomment-752286261) @jedmijares !

However, there is the function [lv_label_set_anim_speed](https://docs.lvgl.io/v6/en/html/object-types/label.html#_CPPv423lv_label_set_anim_speedP8lv_obj_t8uint16_t) in lv_label, couldn't it be used to achieve the same goal (without having to manually scroll the text) ?

**Comment by jedmijares** [comment]
Interesting, I hadn't seen that before. I just tried implementing it and was indeed able to slow down the scrolling, but ran into another error where if the string is too long (not sure how long is too long), the string [will pause before displaying the whole thing and skip back to the beginning instead of scrolling back.](https://www.youtube.com/watch?v=3A7CCb1JHwc)

In any case, since that is another approach, perhaps I should open a separate pull request for comparison's sake?

**Comment by JF002** [comment]
If the function provided by LVGL works the way we want, I would prefer LVGL implementation (so that we don't reinvent the wheel). 
If it's buffy or do not fit our needs, then, a custom implementation will be the way to go ;)

I agree, you can open a 2nd PR for the lvgl implementation and we'll see which one we'll merge into the project !

The video you linked correspond to the lvgl implementation?

**Comment by JF002** [comment]
This was fixed in v1.0.

**Comment by jedmijares** [comment]
Sounds good! I got kind of tied up with school so I'm glad someone else got around to it, ha.

**Comment by JF002** [comment]
Yep, since then, we upgraded LVGL to version 7 and the whole UI have been greatly improved :)

**Pull request closed without merging**
