### PR TITLE
Short vibration when enabling it in quick settings menu

### LINKED ISSUE #271: Very slight detail: Vibration after disabling DND mode
This issue already refers to the BigRewrite version of Infinitime. 
I think it would give Infinitime a bit more convenience if the watch would vibrate for a very short duration after disabling the DND mode on the settings page. I know its a very specific and small detail... But it somehow triggered me while I stumbled across it :)

### PR DESCRIPTION
**Pull request by petterhs**
Goal: Give a short vibration when vibrations are toggled on from the quick settings menu

Fix #271 

I don't have the battery connected to my devkit right now so I'm unable to test if the vibration is working. Perfect if anyone want to test it out for me. Otherwise this will have to wait until i receive my sealed devices.

### CODE REVIEW

**Comment by eivindm** [comment]
Tested your code. I can confirm that it gives a short vibration when you turn vibration on in the settings.

**Comment by petterhs** [comment]
Thanks! 😊

**Comment by pfeerick** [comment]
Just tried it out... seems to work perfectly... turning off notifications does nothing, turning them back on gives a short pulse of vibrator motor. Attached is the DFU I used if anyone wants in in the meantime. 

[pinetime-mcuboot-app-dfu-1.0.0-PR301.zip](https://github.com/JF002/InfiniTime/files/6349675/pinetime-mcuboot-app-dfu-1.0.0-PR301.zip)

**Comment by pfeerick** [comment]
@qbinary See what you think of this ;)

**Comment by qbinary** [comment]
I really like it! Thank you @petterhs for the implementation and thank you @pfeerick for the DFU :)

**Comment by JF002** [comment]
This PR looks good to me, thanks @petterhs ! 
May I ask you to rebase/fix conflicts that appeared since you created this pr so I can merge it?

**Review by JF002 — APPROVED** [review]

**Comment by petterhs** [comment]
Done @JF002 :+1:

**Comment by JF002** [comment]
Thanks :+1:

**Pull request merged**
