### PR TITLE
Improved a bunch of format specifiers

### PR DESCRIPTION
**Pull request by Avamander**
I fixed a missing attribute in LVGL and this allowed me to detect and improve a bunch of format specifiers. 

Hopefully LVGL itself will contain the patch soon as well, but that's yet to be seen.

### CODE REVIEW

**Comment by JF002** [comment]
Do you mean the format specifiers (%d and %i) were incorrect, or are they not supported by lvgl?

**Comment by Avamander** [comment]
They were incorrect for the data type given.

**Comment by JF002** [comment]
Too bad the compiler does not warn us about these type mismatches... or do we just need to add compiler options to enable those warnings?

**Comment by Avamander** [comment]
> or do we just need to add compiler options to enable those warnings?

That, and the LVGL functions have to have an attribute added to them. For the latter I've made a PR to LVGL.

**Pull request merged**
