### PR TITLE
LVGL use system tick

### LINKED ISSUE #435: LVGL Tick gets incremented too fast
LVGL tick tells LVGL how much time has passed.
LVGL tick is incremented in: https://github.com/JF002/InfiniTime/blob/e90e8c7426f9a44e696b208a5b393a60476a3d43/src/main.cpp#L180
According to LVGL documentation, this should happen once every millisecond at most.
https://docs.lvgl.io/latest/en/html/porting/tick.html

However, examining the code of BatteryInfo.cpp shows that even though this task is set to happen once every 1000ms, it happens much more often. This task creates the animation by adding 1% to the bar, and it gets run many times per second.
https://github.com/JF002/InfiniTime/blob/e90e8c7426f9a44e696b208a5b393a60476a3d43/src/displayapp/screens/BatteryInfo.cpp#L69

I tried to move the increment function to vApplicationTickHook(), like the LVGL documentation says, but that seemed to increment much slower. Closer to once every 10ms, making the task run once every 10 seconds.

According to this line tick rate should have been 1024Hz, but maybe this is something else.
https://github.com/JF002/InfiniTime/blob/e90e8c7426f9a44e696b208a5b393a60476a3d43/src/FreeRTOSConfig.h#L62

### PR DESCRIPTION
**Pull request by Riksu9000**
Instead of ticking a separate lvgl counter, let LVGL use the system time.
For every 1000ms lvgl thinks 1024ms have passed, which is close enough, and much closer than before.

Fixes #435 and #306?

### CODE REVIEW

**Comment by JF002** [comment]
Awesome! I didn't know LVGL provided a way to avoid that call to `lv_tick_inc()`! This solution is a lot more elegant and accurate than the original one! :1st_place_medal:

**Comment by JF002** [comment]
Oops! I fixed the conflicts and merge the branch manually, and it looks like Github is not aware of that...

**Comment by JF002** [comment]
@Riksu9000  Could you confirm all your changes have been correctly merged before I close this PR?

**Comment by Riksu9000** [comment]
Everything seems correct and working.

**Comment by JF002** [comment]
Thanks, and sorry for the confusion about this strange merge!

**Comment by Riksu9000** [comment]
Actually there might be a new issue that comes up from the combination of this and the displayapp delay change. Paddle is now more laggy. This is odd as Paddle shouldn't be using lvgl time.

**Pull request closed without merging**
