### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Riksu9000**
Remove unnecessary overrides, and clang-format some files thanks to the pre-commit hook.

### CODE REVIEW

**Comment by JF002** [comment]
Those background labels are there to ensure the whole screen is refreshed when launching a new app. This is needed for the hardware scrolling functionality to work correctly with LVGL. 

I've just tested this branch and... it doesn't seem to work properly : 
bad_hw_scroll

Did you check the code?

**Comment by Riksu9000** [comment]
I thought I tested everything, but I totally forgot to test the digital watch face. Every other app seems to work fine without it though unless I've made another mistake..

**Comment by JF002** [comment]
It may be an issue on my side, then... The display would be corrupted as soon as I scroll up or down... let me test again ;)

**Comment by Riksu9000** [comment]
No I can replicate this as well. These issues only come up when using the digital watch face, all other faces and apps work just fine as far as I can tell.

**Comment by Riksu9000** [comment]
I removed the backgroundLabel changes for now. I would still like to understand better why that happens as it doesn't seem reasonable that some labels are responsible for keeping the display in sync.

Also some more files were changed by the clang-format pre-commit hook. It fits the subject so I kept them.

**Comment by hamblingreen** [comment]
The display corruption seems similar to that of issue #445, just a thought.

**Comment by JF002** [comment]
@hamblingreen good find! So this issue could not be triggered by the modifications in this PR...

**Comment by JF002** [comment]
> I removed the backgroundLabel changes for now. I would still like to understand better why that happens as it doesn't seem reasonable that some labels are responsible for keeping the display in sync.

@Riksu9000 The HW scrolling feature works correctly only when the whole display is updated at once (1 call to LittleVgl::FlushDisplay() with the `area` covering the whole screen. This is a kind of workaround we found to integrate that scrolling feature with LVGL (which doesn't support it natively). 

The analog clock is composed of a background image of 240*240px. When you switch from the analog clock to any other app, and update of the whole screen was needed as destroying the analog clock removes all the widget (and this full screen picture).

The digital clock, on the other side, is composed of many small widget, none of them covering the whole screen. If you switched from the digital clock to another app that doesn't have a widget covering the whole screen, the driver would probably enable the HW scrolling effect but only for a few lines, generating that strange corruption.

I agree, it might be a bit confusing and inefficient, but using these label covering the whole screen allows this mechanism to work correctly :)

**Comment by Riksu9000** [comment]
This is taken from [LVGL 8 documentation](https://docs.lvgl.io/8/porting/display.html#draw-buffer): "In the display driver (lv_disp_drv_t) the full_refresh bit can be enabled to force LVGL to always redraw the whole screen. This works in both one buffer and two buffers modes."

So if there currently isn't a better way to do this, there might be if we update to LVGL 8, assuming this can be changed at runtime.

**Comment by JF002** [comment]
Oooh that's interesting! And a nice incentive to update to LVGL8 !

**Pull request merged**
